# Generated by Django 3.0.3 on 2020-03-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200324_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='sex',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
