# Generated by Django 3.0.3 on 2020-03-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_extenduser_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='goal',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extenduser',
            name='reqCalorie',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extenduser',
            name='reqCarbs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extenduser',
            name='reqFat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extenduser',
            name='reqProtein',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
