# Generated by Django 3.0.3 on 2020-03-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200325_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='activity',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
