# Generated by Django 3.0.3 on 2020-03-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_extenduser_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='sex',
            field=models.CharField(max_length=15),
        ),
    ]
