# Generated by Django 3.0.3 on 2020-03-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200326_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='diet',
            field=models.CharField(default='[]', max_length=300),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='dietStatus',
            field=models.BooleanField(default=False),
        ),
    ]
