# Generated by Django 3.0.3 on 2020-03-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200330_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='diet',
            field=models.CharField(default='{}', max_length=300),
        ),
    ]
