# Generated by Django 3.0.3 on 2020-04-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200330_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='foods',
            field=models.ManyToManyField(blank=True, to='main.food'),
        ),
    ]
