# Generated by Django 3.0.3 on 2020-05-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200508_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='diet',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='dtStatus',
            field=models.CharField(default='Diet not set yet.', max_length=100),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='macroStatus',
            field=models.CharField(default='Your Macronutrients not set currently. Calculate your macronutrients from the calculator given here.', max_length=100),
        ),
    ]
