# Generated by Django 3.0.3 on 2020-05-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200508_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='foods',
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='dtStatus',
            field=models.CharField(default='Diet not set yet.', max_length=200),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='macroStatus',
            field=models.CharField(default='Your Macronutrients not set currently. Calculate your macronutrients from the calculator given here.', max_length=200),
        ),
    ]
